### ISSUE TITLE
can't open or see inside bales

### ISSUE THREAD

**Issue by karelmorlion** [TeamFSIModding/FS17_Goweil_LT_Master#70]
this is a very awesome mod and i use it al the time but since 
the new update, one of my favorite features got removed,
 I am unable to open bales or see whats inside them
is this because this feature was removed or just me?

greetings Karel

**Comment by TyKonKet** [comment]
Are you using the seasons mod?

**Comment by karelmorlion** [comment]
Yes

Op 10-nov.-2017 09:47 schreef "Matteo Autieri" <notifications@github.com>:

**Comment by TyKonKet** [comment]
Ok so, it's not an issue but a change made in this version.
The cutter have been removed, while the seasons is active, because it would create problems with the fermentation process.
The infos about the bales have been removed, while the seasons is active, because the new version of seasons already includes an hand-tool that(the **Wopster**" gives this kind of informations.

**Comment by karelmorlion** [comment]
Thank you for replying so fast
I tought my game was broken
Thank you for your answer!

Op 11-nov.-2017 20:04 schreef "Matteo Autieri" <notifications@github.com>:
