### ISSUE TITLE
cant open bales since lt master update 1.2.0.0 when using seasons mod

### ISSUE THREAD

**Issue by JaysonPhoenix** [TeamFSIModding/FS17_Goweil_LT_Master#71]
since lt master update 1.2.0.0 the open bales feature doesnt work anymore when using seasons mod. (tested with only those 2 mods active and with only lt master active, when using seasons the open bales icon doesnt show and the button doesnt work anymore). probably only a minor error in the added seasons compatibility but couldnt find it myself, please fix asap. 
btw it would have been helpful if there was v1.1.0.0 available here on github and not only 1.0.0.0 for comparing and also for download to use it till you fixed the bug

**Comment by fcelsa** [comment]
This is not a bug, open bales with Seasons active it's no longer available for compatibility reason, see also here #70

**Comment by JaysonPhoenix** [comment]
so if its not a bug but the feature has been disabled for compatibility reasons you should mention that in the changelog or mod description and should and provide the old version on modhub in case somebody doesnt like it that way (like me) and prefers the disabled features and therefor is forced to use the old version. and also as i mentioned here on github for comparing and download.
and what kind of problems would it cause with the fermentation process tho? if seasons is active i didnt see any problems yet if i open wrapped grass bales done by other wrappers, it takes some days for a wrapped grass bale to become a silage bale, if i open em while they are still grass i get a pile of grass and if i open em when they became a silage bale i get a pile of silage, why is your fermentation process and bale opening any different and causing problems?

**Comment by Dzi4d3k** [comment]
> if i open em while they are still grass i get a pile of grass and if i open em when they became a silage bale i get a pile of silage

If I may add my two cents, I would agree. Unless it is unsolvable functions conflict, I would, and suppose, other players also, to get not realistic effect of 80% fermented grass still being grass when open instead of loosing functionality at all.

**Comment by TyKonKet** [comment]
Those are interesting points of view.
We didn't thought that this feature was that much liked from players, since you are also stating that it have't a real conflict with the fermentation process, I'll check and if it works properly, I will enable again that feature, also with seasons.

We apologize for that.

**Comment by TyKonKet** [comment]
Ok, with 0183a898386e7fbbc7ba92f48f8b0374435bfee5 the bale opening is enabled again with seasons.
What i suggest to do, is to download and replace manually [this file](https://github.com/TeamFSIModding/FS17_Goweil_LT_Master/blob/master/src/scripts/baleEviscerator.lua) because in this months the modhub is very slow (for the last update we waited 5 weeks...) so it may take several months to see the new update live.

**Comment by TyKonKet** [comment]
@karelmorlion

**Comment by JaysonPhoenix** [comment]
wow thank you very much :) nice move
